/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppTimelineRouteImport } from './routes/_app/timeline'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppShareIndexRouteImport } from './routes/_app/share/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppShareNewRouteImport } from './routes/_app/share/new'
import { Route as AppReportsUploadRouteImport } from './routes/_app/reports/upload'
import { Route as AppOnboardingProfileRouteImport } from './routes/_app/onboarding/profile'
import { Route as AppOnboardingFirstUploadRouteImport } from './routes/_app/onboarding/first-upload'
import { Route as AppOnboardingDoneRouteImport } from './routes/_app/onboarding/done'
import { Route as AppReportsIdIndexRouteImport } from './routes/_app/reports/$id/index'
import { Route as AppReportsIdEditRouteImport } from './routes/_app/reports/$id/edit'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShareIndexRoute = AppShareIndexRouteImport.update({
  id: '/share/',
  path: '/share/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShareNewRoute = AppShareNewRouteImport.update({
  id: '/share/new',
  path: '/share/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsUploadRoute = AppReportsUploadRouteImport.update({
  id: '/reports/upload',
  path: '/reports/upload',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingProfileRoute = AppOnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingFirstUploadRoute =
  AppOnboardingFirstUploadRouteImport.update({
    id: '/onboarding/first-upload',
    path: '/onboarding/first-upload',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOnboardingDoneRoute = AppOnboardingDoneRouteImport.update({
  id: '/onboarding/done',
  path: '/onboarding/done',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIdIndexRoute = AppReportsIdIndexRouteImport.update({
  id: '/reports/$id/',
  path: '/reports/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsIdEditRoute = AppReportsIdEditRouteImport.update({
  id: '/reports/$id/edit',
  path: '/reports/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/s/$token': typeof STokenRoute
  '/onboarding/done': typeof AppOnboardingDoneRoute
  '/onboarding/first-upload': typeof AppOnboardingFirstUploadRoute
  '/onboarding/profile': typeof AppOnboardingProfileRoute
  '/reports/upload': typeof AppReportsUploadRoute
  '/share/new': typeof AppShareNewRoute
  '/reports/': typeof AppReportsIndexRoute
  '/share/': typeof AppShareIndexRoute
  '/reports/$id/edit': typeof AppReportsIdEditRoute
  '/reports/$id/': typeof AppReportsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/s/$token': typeof STokenRoute
  '/onboarding/done': typeof AppOnboardingDoneRoute
  '/onboarding/first-upload': typeof AppOnboardingFirstUploadRoute
  '/onboarding/profile': typeof AppOnboardingProfileRoute
  '/reports/upload': typeof AppReportsUploadRoute
  '/share/new': typeof AppShareNewRoute
  '/reports': typeof AppReportsIndexRoute
  '/share': typeof AppShareIndexRoute
  '/reports/$id/edit': typeof AppReportsIdEditRoute
  '/reports/$id': typeof AppReportsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/s/$token': typeof STokenRoute
  '/_app/onboarding/done': typeof AppOnboardingDoneRoute
  '/_app/onboarding/first-upload': typeof AppOnboardingFirstUploadRoute
  '/_app/onboarding/profile': typeof AppOnboardingProfileRoute
  '/_app/reports/upload': typeof AppReportsUploadRoute
  '/_app/share/new': typeof AppShareNewRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/share/': typeof AppShareIndexRoute
  '/_app/reports/$id/edit': typeof AppReportsIdEditRoute
  '/_app/reports/$id/': typeof AppReportsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/timeline'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/s/$token'
    | '/onboarding/done'
    | '/onboarding/first-upload'
    | '/onboarding/profile'
    | '/reports/upload'
    | '/share/new'
    | '/reports/'
    | '/share/'
    | '/reports/$id/edit'
    | '/reports/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/timeline'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/s/$token'
    | '/onboarding/done'
    | '/onboarding/first-upload'
    | '/onboarding/profile'
    | '/reports/upload'
    | '/share/new'
    | '/reports'
    | '/share'
    | '/reports/$id/edit'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/$'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/timeline'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/s/$token'
    | '/_app/onboarding/done'
    | '/_app/onboarding/first-upload'
    | '/_app/onboarding/profile'
    | '/_app/reports/upload'
    | '/_app/share/new'
    | '/_app/reports/'
    | '/_app/share/'
    | '/_app/reports/$id/edit'
    | '/_app/reports/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/share/': {
      id: '/_app/share/'
      path: '/share'
      fullPath: '/share/'
      preLoaderRoute: typeof AppShareIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/share/new': {
      id: '/_app/share/new'
      path: '/share/new'
      fullPath: '/share/new'
      preLoaderRoute: typeof AppShareNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/upload': {
      id: '/_app/reports/upload'
      path: '/reports/upload'
      fullPath: '/reports/upload'
      preLoaderRoute: typeof AppReportsUploadRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding/profile': {
      id: '/_app/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AppOnboardingProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding/first-upload': {
      id: '/_app/onboarding/first-upload'
      path: '/onboarding/first-upload'
      fullPath: '/onboarding/first-upload'
      preLoaderRoute: typeof AppOnboardingFirstUploadRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding/done': {
      id: '/_app/onboarding/done'
      path: '/onboarding/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof AppOnboardingDoneRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/$id/': {
      id: '/_app/reports/$id/'
      path: '/reports/$id'
      fullPath: '/reports/$id/'
      preLoaderRoute: typeof AppReportsIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports/$id/edit': {
      id: '/_app/reports/$id/edit'
      path: '/reports/$id/edit'
      fullPath: '/reports/$id/edit'
      preLoaderRoute: typeof AppReportsIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppOnboardingDoneRoute: typeof AppOnboardingDoneRoute
  AppOnboardingFirstUploadRoute: typeof AppOnboardingFirstUploadRoute
  AppOnboardingProfileRoute: typeof AppOnboardingProfileRoute
  AppReportsUploadRoute: typeof AppReportsUploadRoute
  AppShareNewRoute: typeof AppShareNewRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppShareIndexRoute: typeof AppShareIndexRoute
  AppReportsIdEditRoute: typeof AppReportsIdEditRoute
  AppReportsIdIndexRoute: typeof AppReportsIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppOnboardingDoneRoute: AppOnboardingDoneRoute,
  AppOnboardingFirstUploadRoute: AppOnboardingFirstUploadRoute,
  AppOnboardingProfileRoute: AppOnboardingProfileRoute,
  AppReportsUploadRoute: AppReportsUploadRoute,
  AppShareNewRoute: AppShareNewRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppShareIndexRoute: AppShareIndexRoute,
  AppReportsIdEditRoute: AppReportsIdEditRoute,
  AppReportsIdIndexRoute: AppReportsIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
